Task 0
js-tasks-ru/jsbasic-20200903_nursultanunbaev pull request #5
Opened 2020-09-06 08:47 UTC by Sapolsk1

Null Task with function sum(n,m)

2020-09-06 08:54 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ 1+1=2
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-09-07 06:35 UTC, koalex requested changes

2020-09-07 06:35 UTC, koalex commented on 0-module/1-task/index.js
> +sum(1,1);
Убери 12 строку и я поставлю `approve`

2020-09-07 06:59 UTC, koalex commented
Закрываю как дубль https://github.com/js-tasks-ru/jsbasic-20200903_nursultanunbaev/pull/6

2020-09-07 06:59 UTC, closed without merging